// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpiadpugpdqnymydebur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwaWFkcHVncGRxbnlteWRlYnVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NjU0NzQsImV4cCI6MjA2NDQ0MTQ3NH0.c1NhzifHh4aOfUfKZLKBeHNgE-hRwfKdJKZxiLkRRZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);